pipeline {
    agent any
    environment {
        NEW_VERSION = "${env.BUILD_NUMBER}"
    }
    
    stages {
        stage('Checkout') {
            steps {
                git branch: 'app', url: 'https://github.com/dhawal-901/jenkins-task-3.git'
            }
        }     
        stage('Build image') { 
            steps {
                script {
                    app = docker.build("dhawal901/jenkins-task-3","app/")    
                }
            }
        } 
        // stage('Tag image') { 
        //     steps {
        //         script {
        //             sh "docker tag jenkins-task-3 dhawal901/jenkins-task-3:${env.BUILD_NUMBER}"
        //         }
        //     }
        // } 
        stage('Push image') {
            steps {
                script {
                    docker.withRegistry("https://registry.hub.docker.com", "docker-hub") {            
                    //     sh "docker push dhawal901/jenkins-task-3:${env.BUILD_NUMBER}"
                        app.push("${env.BUILD_NUMBER}")
                        app.push("latest")      
                    }
                }
            }    
        }
        stage('Update Compose file'){
            steps{
                script{
                    sh "bash app/update_compose.sh ${NEW_VERSION}"
                }
            }
        }
        stage('Start the service'){
            steps{
                script{
                   sh 'docker compose -f app/compose.yml up -d'
                }
            }
        }
    }
}