

pipeline {
    agent any
    // triggers {
    //     cron('H/5 * * * *')
    // }
    environment{
        CHANNEL_ID= credentials('slack-channel-id') 
    }
    stages {
        stage('Health Check') {
            steps {
                script {
                    def url = 'https://app.test.dhawal.in.net'
                    def response = sh(script: "curl -s -o /dev/null -w '%{http_code}' ${url}", returnStdout: true).trim()

                    if (response == '200') {
                        echo "Applicaton is up and running!"
                    } else {
                        error "Application is unreachable. Status code: ${response}"
                    }
                }
            }
        }
    }

    post {
        always {
            echo 'Health Check Finished!'
        }
        failure {
            echo 'Your Service is down!'
            slackSend(
                channel: "${CHANNEL_ID}", 
                color: 'danger', 
                message: "Your React application running on Nginx with PORT no 80 is down.\n Job: ${env.JOB_NAME}\nBuild Number: #${env.BUILD_NUMBER}.\nBuild_URL:${env.BUILD_URL} Please check immediately",
            )
        }
    }
}
